### ISSUE TITLE
handle string inputs

### ISSUE THREAD

**Issue by aikramer2** [datascienceinc/lime#19]
Lime breaks given training_data like this:

np.array(['a','b'], ['a','b'])

**Comment by pramitchoudhary** [comment]
@aikramer2 possible to provide more detail on this, whats the error that we see ?

**Comment by aikramer2** [comment]
@pramitchoudhary lets close this, this behavior is reasonable.

**Comment by pramitchoudhary** [comment]
oh cool. Thanks @aikramer2
